site_name: My Docs
site_url: https://dnnywang.github.io/

theme:
  name: material
  features:
    - navigation.toc.integrate
    - navigation.tracking
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
